# Generated by Django 3.2.15 on 2025-01-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swinTransformer', '0003_rename_segmented_image_path_segmentedimage_image_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
