# Generated by Django 3.2.15 on 2025-02-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swinTransformer', '0004_user_email'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='originalimage',
            index=models.Index(fields=['user'], name='swinTransfo_user_id_f38b82_idx'),
        ),
        migrations.AddIndex(
            model_name='originalimage',
            index=models.Index(fields=['image_path'], name='swinTransfo_image_p_1e9595_idx'),
        ),
    ]
